title: Portafolio de Ezequiel Isaac Rodríguez Tenorio
email: IsaacRodriguezCH@outlook.com
description: >-
  Portafolio profesional de Ezequiel Isaac Rodríguez Tenorio: backend, inteligencia artificial,
  optimización de sistemas y despliegue de modelos.
baseurl: ""
url: ""
twitter_username: Gta7
github_username: IsokGta7

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
